# Introduction to Data Analysis with pandas

## IEEELearn Coding Workshops



Welcome to the IEEELearn Python workshops, hope you liked all the workshops from morning! 
We will now move to the last workshop in this bootcamp, Data Analysis with pandas

The scope of this workshop will be limited to Data Wrangling and the syntax of python, as learning analysis would require you to learn algorithms like Regression, for which we don't have enough time. Maybe in the next workshop series :)

To start off we will import pandas from the library

In [2]:
import pandas as pd                    #notice the usage of import and the as keyword

### Reading data

The first step for any data analysis project, is to actually have the data. Data can be stored in many file formats like CSV, XLSX, SQL and so on. So the fundamental operation is to read the data. 

Before reading data, you need to know how data is stored when we use pandas. There are two important terms to keep in mind 

1. __Series__ - Series is a sequence of data values. It is analogous to a list which you learnt previously.
2. __DataFrame__ - Dataframe is a an array of individual entries. Each entry has a unique row number and cilumn number. This implies that it is analogous to a table in excel, or a 2-D array in general.

Dataframe is essentially a collection of series' (which in turn are just columns)

We will now create a Dataframe, Series and read data from a CSV file.

In [3]:
pd.Series([1, 2, 3, 4, 5])        #this creates a column containing the values 1,2,3,4,5

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
pd.Series([50, 60, 70], index=['2017 Sales', '2018 Sales', '2019 Sales'], name='Product A sales report')

2017 Sales    50
2018 Sales    60
2019 Sales    70
Name: Product A sales report, dtype: int64

Now that we are comfortable with Series, we will move on to DataFrames

In [5]:
pd.DataFrame({'Yes': [50, 20], 'No': [30, 90]})

   Yes  No
0   50  30
1   20  90

In [6]:
pd.DataFrame({'Bob': ['Meh', 'Duh!'], 'Sue': ['Pffftt..', 'Damnn']})

    Bob       Sue
0   Meh  Pffftt..
1  Duh!     Damnn

In [7]:
pd.DataFrame({'Bob': ['Meh', 'Duh!'], 'Sue': ['Pffftt..', 'Damnn']}, index=['Line 1', 'Line 2'])

         Bob       Sue
Line 1   Meh  Pffftt..
Line 2  Duh!     Damnn

#### Reading CSV files

Being able to create a DataFrame and Series by hand is handy. But, most of the time, we won't actually be creating our own data by hand, we'll be working with data that already exists.

Data can be stored in any of a number of different forms and formats. 

By far the most basic of these is the humble CSV file. When you open a CSV file you get something that looks like this

CSV stands for Comma Separated Value
The following syntax is used to read the csv file stored in a local machine (offline)

In [8]:
wine_reviews = pd.read_csv("winemag-data_first150k.csv")     #since the csv file is in my local path, I can refer it directly, but for files in some other directory, it is better to use the full path

wine_reviews

FileNotFoundError: File b'winemag-data_first150k.csv' does not exist

Incase you want to use a csv file which is online, it can be done in the following way

In [10]:
url = "https://raw.githubusercontent.com/stoltzmaniac/wine-reviews-kaggle/master/winemag-data_first150k.csv"

wine_reviews = pd.read_csv(url)

wine_reviews

,Unnamed: 0,country,description,designation,points,price,province,region_1,region_2,variety,winery
0,0,US,This tremendous 100% varietal wine hails from ...,Martha's Vineyard,96,235.0,California,Napa Valley,Napa,Cabernet Sauvignon,Heitz
1,1,Spain,"Ripe aromas of fig, blackberry and cassis are ...",Carodorum Selección Especial Reserva,96,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
2,2,US,Mac Watson honors the memory of a wine once ma...,Special Selected Late Harvest,96,90.0,California,Knights Valley,Sonoma,Sauvignon Blanc,Macauley
3,3,US,"This spent 20 months in 30% new French oak, an...",Reserve,96,65.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
4,4,France,"This is the top wine from La Bégude, named aft...",La Brûlade,95,66.0,Provence,Bandol,NaN,Provence red blend,Domaine de la Bégude
5,5,Spain,"Deep, dense and pure from the opening bell, th...",Numanthia,95,73.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia
6,6,Spain,Slightly gritty black-fruit aromas include a s...,San Román,95,65.0,Northern Spain,Toro,NaN,Tinta de Toro,Maurodos
7,7,Spain,Lush cedary black-fruit aromas are luxe and of...,Carodorum Único Crianza,95,110.0,Northern Spain,Toro,NaN,Tinta de Toro,Bodega Carmen Rodríguez
8,8,US,This re-named vineyard was formerly bottled as...,Silice,95,65.0,Oregon,Chehalem Mountains,Willamette Valley,Pinot Noir,Bergström
9,9,US,The producer sources from two blocks of the vi...,Gap's Crown Vineyard,95,60.0,California,Sonoma Coast,Sonoma,Pinot Noir,Blue Farm
10,10,Italy,"Elegance, complexity and structure come togeth...",Ronco della Chiesa,95,80.0,Northeastern Italy,Collio,NaN,Friulano,Borgo del Tiglio
11,11,US,"From 18-year-old vines, this supple well-balan...",Estate Vineyard Wadensvil Block,95,48.0,Oregon,Ribbon Ridge,Willamette Valley,Pinot Noir,Patricia Green Cellars
12,12,US,A standout even in this terrific lineup of 201...,Weber Vineyard,95,48.0,Oregon,Dundee Hills,Willamette Valley,Pinot Noir,Patricia Green Cellars
13,13,France,This wine is in peak condition. The tannins an...,Château Montus Prestige,95,90.0,Southwest France,Madiran,NaN,Tannat,Vignobles Brumont
14,14,US,"With its sophisticated mix of mineral, acid an...",Grace Vineyard,95,185.0,Oregon,Dundee Hills,Willamette Valley,Pinot Noir,Domaine Serene
15,15,US,"First made in 2006, this succulent luscious Ch...",Sigrid,95,90.0,Oregon,Willamette Valley,Willamette Valley,Chardonnay,Bergström
16,16,US,"This blockbuster, powerhouse of a wine suggest...",Rainin Vineyard,95,325.0,California,Diamond Mountain District,Napa,Cabernet Sauvignon,Hall
17,17,Spain,"Nicely oaked blackberry, licorice, vanilla and...",6 Años Reserva Premium,95,80.0,Northern Spain,Ribera del Duero,NaN,Tempranillo,Valduero
18,18,France,Coming from a seven-acre vineyard named after ...,Le Pigeonnier,95,290.0,Southwest France,Cahors,NaN,Malbec,Château Lagrézette
19,19,US,This fresh and lively medium-bodied wine is be...,Gap's Crown Vineyard,95,75.0,California,Sonoma Coast,Sonoma,Pinot Noir,Gary Farrell
20,20,US,Heitz has made this stellar rosé from the rare...,Grignolino,95,24.0,California,Napa Valley,Napa,Rosé,Heitz
21,21,Spain,"Alluring, complex and powerful aromas of grill...",Prado Enea Gran Reserva,95,79.0,Northern Spain,Rioja,NaN,Tempranillo Blend,Muga
22,22,Spain,Tarry blackberry and cheesy oak aromas are app...,Termanthia,95,220.0,Northern Spain,Toro,NaN,Tinta de Toro,Numanthia
23,23,US,The apogee of this ambitious winery's white wi...,Giallo Solare,95,60.0,California,Edna Valley,Central Coast,Chardonnay,Center of Effort
24,24,US,"San Jose-based producer Adam Comartin heads 1,...",R-Bar-R Ranch,95,45.0,California,Santa Cruz Mountains,Central Coast,Pinot Noir,Comartin
25,25,New Zealand,"Yields were down in 2015, but intensity is up,...",Maté's Vineyard,94,57.0,Kumeu,NaN,NaN,Chardonnay,Kumeu River
26,26,US,Bergström has made a Shea designate since 2003...,Shea Vineyard,94,62.0,Oregon,Willamette Valley,NaN,Pinot Noir,Bergström
27,27,US,"Focused and dense, this intense wine captures ...",Abetina,94,105.0,Oregon,Willamette Valley,Willamette Valley,Pinot Noir,Ponzi
28,28,US,"Cranberry, baked rhubarb, anise and crushed sl...",Garys' Vineyard,94,60.0,California,Santa Lucia Highlands,Central Coast,Pinot Noir,Roar
29,29,US,This standout Rocks District wine brings earth...,The Funk Estate,94,60.0,Washington,Walla Walla Valley (WA),Columbia Valley,Syrah,Saviah
...,...,...,...,...,...,...,...,...,...,...,...
150900,150900,Chile,"Aromas of freshly cut lumber, complete with so...",Prima Reserva,81,13.0,Maipo Valley,NaN,NaN,Cabernet Sauvignon,De Martino
150901,150901,Chile,"Lavishly oaked, the fruit here struggles to ma...",Reserva,81,12.0,Maipo Valley,NaN,NaN,Merlot,Undurraga
150902,150902,Chile,This medium weight Chardonnay offered aromas o...,Estate Bottled,81,10.0,Maipo Valley,NaN,NaN,Chardonnay,De Martino
150903,150903,Chile,Very light berry and mint aromas open this aus...,120,81,7.0,Rapel Valley,NaN,NaN,Cabernet Sauvignon,Santa Rita
150904,150904,Chile,A lot of Chilean Cabernets seem to have a dist...,NaN,81,10.0,Maipo Valley,NaN,NaN,Cabernet Sauvignon,De Martino
150905,150905,Chile,There's not much point in making a reserve-sty...,Prima Reserva,80,13.0,Maipo Valley,NaN,NaN,Merlot,De Martino
150906,150906,France,"This lovely wine, a Monopole, is already showi...",Clos des Reas,93,65.0,Burgundy,Vosne-Romanée,NaN,Pinot Noir,Michel Gros
150907,150907,France,"Rion holds back on the new oak, letting the pu...",Les Beaux-Monts,92,52.0,Burgundy,Vosne-Romanée,NaN,Pinot Noir,Daniel Rion
150908,150908,France,"Another premier cru from Michel Gros, this one...",Aux Brulees,90,65.0,Burgundy,Vosne-Romanée,NaN,Pinot Noir,Michel Gros
150909,150909,France,"This is a lovely, fragrant Burgundy, with a sm...",Clos dea Argillieres,89,52.0,Burgundy,Nuits-St.-Georges,NaN,Pinot Noir,Daniel Rion
150910,150910,France,Scents of graham cracker and malted milk choco...,NaN,89,38.0,Burgundy,Chambolle-Musigny,NaN,Pinot Noir,Michel Gros
150911,150911,France,"This needs a good bit of breathing time, then ...",Les Chaliots,87,37.0,Burgundy,Nuits-St.-Georges,NaN,Pinot Noir,Michel Gros
150912,150912,France,The nose is dominated by the attractive scents...,Les Charmes,87,65.0,Burgundy,Chambolle-Musigny,NaN,Pinot Noir,Daniel Rion
150913,150913,France,"Inky and rustic, yet in a refined manner. This...",NaN,94,30.0,Rhône Valley,Châteauneuf-du-Pape,NaN,Rhône-style Red Blend,Le Vieux Donjon
150914,150914,US,"Old-gold in color, and thick and syrupy. The a...",Late Harvest Cluster Select,94,25.0,California,Anderson Valley,Mendocino/Lake Counties,White Riesling,Navarro
150915,150915,US,"Decades ago, Beringer’s then-winemaker Myron N...",Nightingale,93,30.0,California,North Coast,North Coast,White Blend,Beringer
150916,150916,US,An impressive wine that presents a full bouque...,J. Schram,93,65.0,California,Napa Valley,Napa,Champagne Blend,Schramsberg
150917,150917,France,"Light and elegant, this spicy, lively wine is ...",Brut Mosaïque,92,30.0,Champagne,Champagne,NaN,Champagne Blend,Jacquart
150918,150918,France,"Jacquart makes a full-bodied, ripe style of Ch...",Cuvée Mosaïque,92,38.0,Champagne,Champagne,NaN,Champagne Blend,Jacquart
150919,150919,France,This classy example opens with a very floral n...,Cuvée President,91,37.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150920,150920,Italy,"Rich and mature aromas of smoke, earth and her...",Brut Riserva,91,19.0,Northeastern Italy,Trento,NaN,Champagne Blend,Letrari
150921,150921,France,Shows some older notes: a bouquet of toasted w...,Blanc de Blancs Brut Mosaïque,91,38.0,Champagne,Champagne,NaN,Champagne Blend,Jacquart
150922,150922,Italy,Made by 30-ish Roberta Borghese high above Man...,Superiore,91,NaN,Northeastern Italy,Colli Orientali del Friuli,NaN,Tocai,Ronchi di Manzano
150923,150923,France,"Rich and toasty, with tiny bubbles. The bouque...",Demi-Sec,91,30.0,Champagne,Champagne,NaN,Champagne Blend,Jacquart
150924,150924,France,"Really fine for a low-acid vintage, there's an...",Diamant Bleu,91,70.0,Champagne,Champagne,NaN,Champagne Blend,Heidsieck & Co Monopole
150925,150925,Italy,Many people feel Fiano represents southern Ita...,NaN,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Feudi di San Gregorio
150926,150926,France,"Offers an intriguing nose with ginger, lime an...",Cuvée Prestige,91,27.0,Champagne,Champagne,NaN,Champagne Blend,H.Germain
150927,150927,Italy,This classic example comes from a cru vineyard...,Terre di Dora,91,20.0,Southern Italy,Fiano di Avellino,NaN,White Blend,Terredora
150928,150928,France,"A perfect salmon shade, with scents of peaches...",Grand Brut Rosé,90,52.0,Champagne,Champagne,NaN,Champagne Blend,Gosset
150929,150929,Italy,More Pinot Grigios should taste like this. A r...,NaN,90,15.0,Northeastern Italy,Alto Adige,NaN,Pinot Grigio,Alois Lageder

We will now go through some of the common functionalities that can be done on a dataframe after it is loaded

Please refer to this cheatsheet for a quick reference at all times. 
[Pandas Cheatsheet](https://s3.amazonaws.com/assets.datacamp.com/blog_assets/PandasPythonForDataScience.pdf)

In [11]:
wine_reviews.shape     # shape returns the size of the dataframe (rows, colums)

(150930, 11)

In [12]:
wine_reviews.head     # returns the top few results from the dataset

<bound method NDFrame.head of         Unnamed: 0      country  \
0                0           US
1                1        Spain
2                2           US
3                3           US
4                4       France
5                5        Spain
6                6        Spain
7                7        Spain
8                8           US
9                9           US
10              10        Italy
11              11           US
12              12           US
13              13       France
14              14           US
15              15           US
16              16           US
17              17        Spain
18              18       France
19              19           US
20              20           US
21              21        Spain
22              22        Spain
23              23           US
24              24           US
25              25  New Zealand
26              26           US
27              27           US
28              28           US
29              29           US
...            ...          ...
150900      150900        Chile
150901      150901        Chile
150902      150902        Chile
150903      150903        Chile
150904      150904        Chile
150905      150905        Chile
150906      150906       France
150907      150907       France
150908      150908       France
150909      150909       France
150910      150910       France
150911      150911       France
150912      150912       France
150913      150913       France
150914      150914           US
150915      150915           US
150916      150916           US
150917      150917       France
150918      150918       France
150919      150919       France
150920      150920        Italy
150921      150921       France
150922      150922        Italy
150923      150923       France
150924      150924       France
150925      150925        Italy
150926      150926       France
150927      150927        Italy
150928      150928       France
150929      150929        Italy

                                              description  \
0       This tremendous 100% varietal wine hails from ...
1       Ripe aromas of fig, blackberry and cassis are ...
2       Mac Watson honors the memory of a wine once ma...
3       This spent 20 months in 30% new French oak, an...
4       This is the top wine from La Bégude, named aft...
5       Deep, dense and pure from the opening bell, th...
6       Slightly gritty black-fruit aromas include a s...
7       Lush cedary black-fruit aromas are luxe and of...
8       This re-named vineyard was formerly bottled as...
9       The producer sources from two blocks of the vi...
10      Elegance, complexity and structure come togeth...
11      From 18-year-old vines, this supple well-balan...
12      A standout even in this terrific lineup of 201...
13      This wine is in peak condition. The tannins an...
14      With its sophisticated mix of mineral, acid an...
15      First made in 2006, this succulent luscious Ch...
16      This blockbuster, powerhouse of a wine suggest...
17      Nicely oaked blackberry, licorice, vanilla and...
18      Coming from a seven-acre vineyard named after ...
19      This fresh and lively medium-bodied wine is be...
20      Heitz has made this stellar rosé from the rare...
21      Alluring, complex and powerful aromas of grill...
22      Tarry blackberry and cheesy oak aromas are app...
23      The apogee of this ambitious winery's white wi...
24      San Jose-based producer Adam Comartin heads 1,...
25      Yields were down in 2015, but intensity is up,...
26      Bergström has made a Shea designate since 2003...
27      Focused and dense, this intense wine captures ...
28      Cranberry, baked rhubarb, anise and crushed sl...
29      This standout Rocks District wine brings earth...
...                                                   ...
150900  Aromas of freshly cut lumber, complete with so...
150901  Lavishly oaked, the fruit here struggles to ma...
150902  This medium weight Chardonnay offered aromas o...
150903  Very light berry and mint aromas open this aus...
150904  A lot of Chilean Cabernets seem to have a dist...
150905  There's not much point in making a reserve-sty...
150906  This lovely wine, a Monopole, is already showi...
150907  Rion holds back on the new oak, letting the pu...
150908  Another premier cru from Michel Gros, this one...
150909  This is a lovely, fragrant Burgundy, with a sm...
150910  Scents of graham cracker and malted milk choco...
150911  This needs a good bit of breathing time, then ...
150912  The nose is dominated by the attractive scents...
150913  Inky and rustic, yet in a refined manner. This...
150914  Old-gold in color, and thick and syrupy. The a...
150915  Decades ago, Beringer’s then-winemaker Myron N...
150916  An impressive wine that presents a full bouque...
150917  Light and elegant, this spicy, lively wine is ...
150918  Jacquart makes a full-bodied, ripe style of Ch...
150919  This classy example opens with a very floral n...
150920  Rich and mature aromas of smoke, earth and her...
150921  Shows some older notes: a bouquet of toasted w...
150922  Made by 30-ish Roberta Borghese high above Man...
150923  Rich and toasty, with tiny bubbles. The bouque...
150924  Really fine for a low-acid vintage, there's an...
150925  Many people feel Fiano represents southern Ita...
150926  Offers an intriguing nose with ginger, lime an...
150927  This classic example comes from a cru vineyard...
150928  A perfect salmon shade, with scents of peaches...
150929  More Pinot Grigios should taste like this. A r...

                                 designation  points  price  \
0                          Martha's Vineyard      96  235.0
1       Carodorum Selección Especial Reserva      96  110.0
2              Special Selected Late Harvest      96   90.0
3                                    Reserve      96   65.0
4                                 La Brûlade      95   66.0
5                                  Numanthia      95   73.0
6                                  San Román      95   65.0
7                    Carodorum Único Crianza      95  110.0
8                                     Silice      95   65.0
9                       Gap's Crown Vineyard      95   60.0
10                        Ronco della Chiesa      95   80.0
11           Estate Vineyard Wadensvil Block      95   48.0
12                            Weber Vineyard      95   48.0
13                   Château Montus Prestige      95   90.0
14                            Grace Vineyard      95  185.0
15                                    Sigrid      95   90.0
16                           Rainin Vineyard      95  325.0
17                    6 Años Reserva Premium      95   80.0
18                             Le Pigeonnier      95  290.0
19                      Gap's Crown Vineyard      95   75.0
20                                Grignolino      95   24.0
21                   Prado Enea Gran Reserva      95   79.0
22                                Termanthia      95  220.0
23                             Giallo Solare      95   60.0
24                             R-Bar-R Ranch      95   45.0
25                           Maté's Vineyard      94   57.0
26                             Shea Vineyard      94   62.0
27                                   Abetina      94  105.0
28                           Garys' Vineyard      94   60.0
29                           The Funk Estate      94   60.0
...                                      ...     ...    ...
150900                         Prima Reserva      81   13.0
150901                               Reserva      81   12.0
150902                        Estate Bottled      81   10.0
150903                                   120      81    7.0
150904                                   NaN      81   10.0
150905                         Prima Reserva      80   13.0
150906                         Clos des Reas      93   65.0
150907                       Les Beaux-Monts      92   52.0
150908                           Aux Brulees      90   65.0
150909                  Clos dea Argillieres      89   52.0
150910                                   NaN      89   38.0
150911                          Les Chaliots      87   37.0
150912                           Les Charmes      87   65.0
150913                                   NaN      94   30.0
150914           Late Harvest Cluster Select      94   25.0
150915                           Nightingale      93   30.0
150916                             J. Schram      93   65.0
150917                         Brut Mosaïque      92   30.0
150918                        Cuvée Mosaïque      92   38.0
150919                       Cuvée President      91   37.0
150920                          Brut Riserva      91   19.0
150921         Blanc de Blancs Brut Mosaïque      91   38.0
150922                             Superiore      91    NaN
150923                              Demi-Sec      91   30.0
150924                          Diamant Bleu      91   70.0
150925                                   NaN      91   20.0
150926                        Cuvée Prestige      91   27.0
150927                         Terre di Dora      91   20.0
150928                       Grand Brut Rosé      90   52.0
150929                                   NaN      90   15.0

                  province                    region_1  \
0               California                 Napa Valley
1           Northern Spain                        Toro
2               California              Knights Valley
3                   Oregon           Willamette Valley
4                 Provence                      Bandol
5           Northern Spain                        Toro
6           Northern Spain                        Toro
7           Northern Spain                        Toro
8                   Oregon          Chehalem Mountains
9               California                Sonoma Coast
10      Northeastern Italy                      Collio
11                  Oregon                Ribbon Ridge
12                  Oregon                Dundee Hills
13        Southwest France                     Madiran
14                  Oregon                Dundee Hills
15                  Oregon           Willamette Valley
16              California   Diamond Mountain District
17          Northern Spain            Ribera del Duero
18        Southwest France                      Cahors
19              California                Sonoma Coast
20              California                 Napa Valley
21          Northern Spain                       Rioja
22          Northern Spain                        Toro
23              California                 Edna Valley
24              California        Santa Cruz Mountains
25                   Kumeu                         NaN
26                  Oregon           Willamette Valley
27                  Oregon           Willamette Valley
28              California       Santa Lucia Highlands
29              Washington     Walla Walla Valley (WA)
...                    ...                         ...
150900        Maipo Valley                         NaN
150901        Maipo Valley                         NaN
150902        Maipo Valley                         NaN
150903        Rapel Valley                         NaN
150904        Maipo Valley                         NaN
150905        Maipo Valley                         NaN
150906            Burgundy               Vosne-Romanée
150907            Burgundy               Vosne-Romanée
150908            Burgundy               Vosne-Romanée
150909            Burgundy           Nuits-St.-Georges
150910            Burgundy           Chambolle-Musigny
150911            Burgundy           Nuits-St.-Georges
150912            Burgundy           Chambolle-Musigny
150913        Rhône Valley         Châteauneuf-du-Pape
150914          California             Anderson Valley
150915          California                 North Coast
150916          California                 Napa Valley
150917           Champagne                   Champagne
150918           Champagne                   Champagne
150919           Champagne                   Champagne
150920  Northeastern Italy                      Trento
150921           Champagne                   Champagne
150922  Northeastern Italy  Colli Orientali del Friuli
150923           Champagne                   Champagne
150924           Champagne                   Champagne
150925      Southern Italy           Fiano di Avellino
150926           Champagne                   Champagne
150927      Southern Italy           Fiano di Avellino
150928           Champagne                   Champagne
150929  Northeastern Italy                  Alto Adige

                       region_2                variety  \
0                          Napa     Cabernet Sauvignon
1                           NaN          Tinta de Toro
2                        Sonoma        Sauvignon Blanc
3             Willamette Valley             Pinot Noir
4                           NaN     Provence red blend
5                           NaN          Tinta de Toro
6                           NaN          Tinta de Toro
7                           NaN          Tinta de Toro
8             Willamette Valley             Pinot Noir
9                        Sonoma             Pinot Noir
10                          NaN               Friulano
11            Willamette Valley             Pinot Noir
12            Willamette Valley             Pinot Noir
13                          NaN                 Tannat
14            Willamette Valley             Pinot Noir
15            Willamette Valley             Chardonnay
16                         Napa     Cabernet Sauvignon
17                          NaN            Tempranillo
18                          NaN                 Malbec
19                       Sonoma             Pinot Noir
20                         Napa                   Rosé
21                          NaN      Tempranillo Blend
22                          NaN          Tinta de Toro
23                Central Coast             Chardonnay
24                Central Coast             Pinot Noir
25                          NaN             Chardonnay
26                          NaN             Pinot Noir
27            Willamette Valley             Pinot Noir
28                Central Coast             Pinot Noir
29              Columbia Valley                  Syrah
...                         ...                    ...
150900                      NaN     Cabernet Sauvignon
150901                      NaN                 Merlot
150902                      NaN             Chardonnay
150903                      NaN     Cabernet Sauvignon
150904                      NaN     Cabernet Sauvignon
150905                      NaN                 Merlot
150906                      NaN             Pinot Noir
150907                      NaN             Pinot Noir
150908                      NaN             Pinot Noir
150909                      NaN             Pinot Noir
150910                      NaN             Pinot Noir
150911                      NaN             Pinot Noir
150912                      NaN             Pinot Noir
150913                      NaN  Rhône-style Red Blend
150914  Mendocino/Lake Counties         White Riesling
150915              North Coast            White Blend
150916                     Napa        Champagne Blend
150917                      NaN        Champagne Blend
150918                      NaN        Champagne Blend
150919                      NaN        Champagne Blend
150920                      NaN        Champagne Blend
150921                      NaN        Champagne Blend
150922                      NaN                  Tocai
150923                      NaN        Champagne Blend
150924                      NaN        Champagne Blend
150925                      NaN            White Blend
150926                      NaN        Champagne Blend
150927                      NaN            White Blend
150928                      NaN        Champagne Blend
150929                      NaN           Pinot Grigio

                         winery
0                         Heitz
1       Bodega Carmen Rodríguez
2                      Macauley
3                         Ponzi
4          Domaine de la Bégude
5                     Numanthia
6                      Maurodos
7       Bodega Carmen Rodríguez
8                     Bergström
9                     Blue Farm
10             Borgo del Tiglio
11       Patricia Green Cellars
12       Patricia Green Cellars
13            Vignobles Brumont
14               Domaine Serene
15                    Bergström
16                         Hall
17                     Valduero
18           Château Lagrézette
19                 Gary Farrell
20                        Heitz
21                         Muga
22                    Numanthia
23             Center of Effort
24                     Comartin
25                  Kumeu River
26                    Bergström
27                        Ponzi
28                         Roar
29                       Saviah
...                         ...
150900               De Martino
150901                Undurraga
150902               De Martino
150903               Santa Rita
150904               De Martino
150905               De Martino
150906              Michel Gros
150907              Daniel Rion
150908              Michel Gros
150909              Daniel Rion
150910              Michel Gros
150911              Michel Gros
150912              Daniel Rion
150913          Le Vieux Donjon
150914                  Navarro
150915                 Beringer
150916              Schramsberg
150917                 Jacquart
150918                 Jacquart
150919                H.Germain
150920                  Letrari
150921                 Jacquart
150922        Ronchi di Manzano
150923                 Jacquart
150924  Heidsieck & Co Monopole
150925    Feudi di San Gregorio
150926                H.Germain
150927                Terredora
150928                   Gosset
150929            Alois Lageder

[150930 rows x 11 columns]>

We will now look at a few of the important summarization functions. It can be done by `describe` function

We will now obtain the summary of the column `points`

In [13]:
wine_reviews.points.describe()

count    150930.000000
mean         87.888418
std           3.222392
min          80.000000
25%          86.000000
50%          88.000000
75%          90.000000
max         100.000000
Name: points, dtype: float64

As you can see the `describe` function works for numerical data. What about for string data ?

In [14]:
wine_reviews.country.describe()

count     150925
unique        48
top           US
freq       62397
Name: country, dtype: object

To get the average points, we use the `mean` function. 

To view the unique values in the dataset, we use the `unique` function

To view the frequency of the unique values, we use the `value_counts` function

In [15]:
wine_reviews.points.mean()

87.8884184721394

In [16]:
wine_reviews.country.unique()

array(['US', 'Spain', 'France', 'Italy', 'New Zealand', 'Bulgaria',
       'Argentina', 'Australia', 'Portugal', 'Israel', 'South Africa',
       'Greece', 'Chile', 'Morocco', 'Romania', 'Germany', 'Canada',
       'Moldova', 'Hungary', 'Austria', 'Croatia', 'Slovenia', nan,
       'India', 'Turkey', 'Macedonia', 'Lebanon', 'Serbia', 'Uruguay',
       'Switzerland', 'Albania', 'Bosnia and Herzegovina', 'Brazil',
       'Cyprus', 'Lithuania', 'Japan', 'China', 'South Korea', 'Ukraine',
       'England', 'Mexico', 'Georgia', 'Montenegro', 'Luxembourg',
       'Slovakia', 'Czech Republic', 'Egypt', 'Tunisia', 'US-France'],
      dtype=object)

In [17]:
wine_reviews.country.value_counts()

US                        62397
Italy                     23478
France                    21098
Spain                      8268
Chile                      5816
Argentina                  5631
Portugal                   5322
Australia                  4957
New Zealand                3320
Austria                    3057
Germany                    2452
South Africa               2258
Greece                      884
Israel                      630
Hungary                     231
Canada                      196
Romania                     139
Slovenia                     94
Uruguay                      92
Croatia                      89
Bulgaria                     77
Moldova                      71
Mexico                       63
Turkey                       52
Georgia                      43
Lebanon                      37
Cyprus                       31
Brazil                       25
Macedonia                    16
Serbia                       14
Morocco                      12
Luxembourg                    9
England                       9
Lithuania                     8
India                         8
Czech Republic                6
Ukraine                       5
Switzerland                   4
Bosnia and Herzegovina        4
South Korea                   4
Egypt                         3
Slovakia                      3
China                         3
Montenegro                    2
Albania                       2
Tunisia                       2
Japan                         2
US-France                     1
Name: country, dtype: int64

Grouping can be used for many purposes. You've already used the `value_counts` function. We can replicate what `value_counts` does using groupby by doing the following:

In [18]:
wine_reviews.groupby('country').country.count()

country
Albania                       2
Argentina                  5631
Australia                  4957
Austria                    3057
Bosnia and Herzegovina        4
Brazil                       25
Bulgaria                     77
Canada                      196
Chile                      5816
China                         3
Croatia                      89
Cyprus                       31
Czech Republic                6
Egypt                         3
England                       9
France                    21098
Georgia                      43
Germany                    2452
Greece                      884
Hungary                     231
India                         8
Israel                      630
Italy                     23478
Japan                         2
Lebanon                      37
Lithuania                     8
Luxembourg                    9
Macedonia                    16
Mexico                       63
Moldova                      71
Montenegro                    2
Morocco                      12
New Zealand                3320
Portugal                   5322
Romania                     139
Serbia                       14
Slovakia                      3
Slovenia                     94
South Africa               2258
South Korea                   4
Spain                      8268
Switzerland                   4
Tunisia                       2
Turkey                       52
US                        62397
US-France                     1
Ukraine                       5
Uruguay                      92
Name: country, dtype: int64

There are a few __aggregation__ functions we can use with `groupby` to perform operations. 
A few of them are :
+ `max`
+ `min`

In [19]:
max_points = wine_reviews.groupby('points').price.max()
min_points = wine_reviews.groupby('points').price.min()

max_points
min_points

points
80      5.0
81      5.0
82      5.0
83      4.0
84      4.0
85      4.0
86      4.0
87      6.0
88      6.0
89      7.0
90      5.0
91      8.0
92     11.0
93     12.0
94     15.0
95     20.0
96     20.0
97     42.0
98     50.0
99     65.0
100    65.0
Name: price, dtype: float64

Another groupby method worth mentioning is `agg`, which lets you run a bunch of different functions on your DataFrame simultaneously. For example, we can generate a simple statistical summary of the dataset as follows:

In [20]:
wine_reviews.groupby(['country']).price.agg([len, min, max])

                            len   min     max
country
Albania                     2.0  20.0    20.0
Argentina                5631.0   4.0   250.0
Australia                4957.0   5.0   850.0
Austria                  3057.0   8.0  1100.0
Bosnia and Herzegovina      4.0  12.0    13.0
Brazil                     25.0  11.0    35.0
Bulgaria                   77.0   7.0    28.0
Canada                    196.0  12.0   145.0
Chile                    5816.0   5.0   400.0
China                       3.0   7.0    27.0
Croatia                    89.0  12.0    65.0
Cyprus                     31.0  10.0    22.0
Czech Republic              6.0  15.0    25.0
Egypt                       3.0   NaN     NaN
England                     9.0  38.0    75.0
France                  21098.0   5.0  2300.0
Georgia                    43.0   9.0    40.0
Germany                  2452.0   5.0   775.0
Greece                    884.0   7.0   120.0
Hungary                   231.0   7.0   764.0
India                       8.0  10.0    20.0
Israel                    630.0   8.0   150.0
Italy                   23478.0   5.0   900.0
Japan                       2.0  24.0    24.0
Lebanon                    37.0  12.0    51.0
Lithuania                   8.0  10.0    10.0
Luxembourg                  9.0  36.0    50.0
Macedonia                  16.0  12.0    25.0
Mexico                     63.0  12.0   108.0
Moldova                    71.0   8.0    42.0
Montenegro                  2.0  10.0    10.0
Morocco                    12.0   6.0    35.0
New Zealand              3320.0   7.0   125.0
Portugal                 5322.0   4.0   980.0
Romania                   139.0   4.0   320.0
Serbia                     14.0  15.0    42.0
Slovakia                    3.0  15.0    16.0
Slovenia                   94.0   7.0    90.0
South Africa             2258.0   5.0   145.0
South Korea                 4.0  11.0    16.0
Spain                    8268.0   4.0   770.0
Switzerland                 4.0  19.0    38.0
Tunisia                     2.0   NaN     NaN
Turkey                     52.0  14.0   120.0
US                      62397.0   4.0  2013.0
US-France                   1.0  50.0    50.0
Ukraine                     5.0  13.0    13.0
Uruguay                    92.0   7.0    60.0

We will now see something called as `multi-index`. It has multiple levels

In [21]:
countries_reviewed = wine_reviews.groupby(['country', 'province']).description.agg([len])
countries_reviewed

                                          len
country   province
Albania   Mirditë                           2
Argentina Mendoza Province               4742
          Other                           889
Australia Australia Other                 553
          New South Wales                 246
          Queensland                        3
          South Australia                3004
          Tasmania                         47
          Victoria                        613
          Western Australia               491
Austria   Austria                          19
          Burgenland                      764
          Carnuntum                        70
          Donauland                        22
          Eisenberg                         3
          Kamptal                         327
          Kremstal                        318
          Langenlois                        1
          Leithaberg                        6
          Mittelburgenland                 48
          Neusiedlersee                    36
          Neusiedlersee-Hügelland          43
          Niederösterreich                491
          South Styria                      3
          Steiermark                        7
          Styria                           15
          Südoststeiermark                 57
          Südsteiermark                    64
          Thermenregion                   122
          Traisental                       24
...                                       ...
US        Idaho                           136
          Iowa                              4
          Kentucky                          4
          Massachusetts                    10
          Michigan                         25
          Missouri                         60
          Nevada                            1
          New Jersey                       24
          New Mexico                       95
          New York                       2428
          North Carolina                   20
          Ohio                             34
          Oregon                         4589
          Pennsylvania                     50
          Texas                            41
          Vermont                           2
          Virginia                        515
          Washington                     9750
          Washington-Oregon                 3
US-France Santa Barbara County-Condrieu     1
Ukraine   Ukraine                           5
Uruguay   Atlantida                         4
          Canelones                        19
          Colonia                           6
          El Colorado                       3
          Juanico                          19
          Montevideo                        3
          Progreso                          5
          San Jose                         15
          Uruguay                          18

[455 rows x 1 columns]

To convert the multi index to the normal index, we will use the `reset_index` function.

In [22]:
countries_reviewed.reset_index()

       country                       province   len
0      Albania                        Mirditë     2
1    Argentina               Mendoza Province  4742
2    Argentina                          Other   889
3    Australia                Australia Other   553
4    Australia                New South Wales   246
5    Australia                     Queensland     3
6    Australia                South Australia  3004
7    Australia                       Tasmania    47
8    Australia                       Victoria   613
9    Australia              Western Australia   491
10     Austria                        Austria    19
11     Austria                     Burgenland   764
12     Austria                      Carnuntum    70
13     Austria                      Donauland    22
14     Austria                      Eisenberg     3
15     Austria                        Kamptal   327
16     Austria                       Kremstal   318
17     Austria                     Langenlois     1
18     Austria                     Leithaberg     6
19     Austria               Mittelburgenland    48
20     Austria                  Neusiedlersee    36
21     Austria        Neusiedlersee-Hügelland    43
22     Austria               Niederösterreich   491
23     Austria                   South Styria     3
24     Austria                     Steiermark     7
25     Austria                         Styria    15
26     Austria               Südoststeiermark    57
27     Austria                  Südsteiermark    64
28     Austria                  Thermenregion   122
29     Austria                     Traisental    24
..         ...                            ...   ...
425         US                          Idaho   136
426         US                           Iowa     4
427         US                       Kentucky     4
428         US                  Massachusetts    10
429         US                       Michigan    25
430         US                       Missouri    60
431         US                         Nevada     1
432         US                     New Jersey    24
433         US                     New Mexico    95
434         US                       New York  2428
435         US                 North Carolina    20
436         US                           Ohio    34
437         US                         Oregon  4589
438         US                   Pennsylvania    50
439         US                          Texas    41
440         US                        Vermont     2
441         US                       Virginia   515
442         US                     Washington  9750
443         US              Washington-Oregon     3
444  US-France  Santa Barbara County-Condrieu     1
445    Ukraine                        Ukraine     5
446    Uruguay                      Atlantida     4
447    Uruguay                      Canelones    19
448    Uruguay                        Colonia     6
449    Uruguay                    El Colorado     3
450    Uruguay                        Juanico    19
451    Uruguay                     Montevideo     3
452    Uruguay                       Progreso     5
453    Uruguay                       San Jose    15
454    Uruguay                        Uruguay    18

[455 rows x 3 columns]

## Sorting

You can sort the data by using the `sort_values` method

In [23]:
countries_reviewed = countries_reviewed.reset_index()
countries_reviewed.sort_values(by='len')

          country                       province    len
154        Greece                 Central Greece      1
207        Greece                          Zitsa      1
115        Cyprus                          Pafos      1
362      Slovenia                Slovenska Istra      1
213       Hungary                         Pannon      1
302      Portugal                 Douro Superior      1
357      Slovenia                      Dolenjska      1
353        Serbia                       Pocerina      1
42         Brazil               Serra do Sudeste      1
43         Brazil                  Vale Trentino      1
349       Romania                    Viile Timis      1
348       Romania                Viile Carasului      1
49       Bulgaria                    Rose Valley      1
99        Croatia                Dalmatian Coast      1
346       Romania               Terasele Dunarii      1
95          Chile                   San Clemente      1
259       Morocco                     Beni M'Tir      1
261       Morocco                        Morocco      1
266   New Zealand      Central Otago-Marlborough      1
275   New Zealand          Martinborough Terrace      1
64          Chile       Casablanca-Curicó Valley      1
82          Chile  Maipo Valley-Colchagua Valley      1
283   New Zealand                       Stirling      1
289   New Zealand                 Waitaki Valley      1
69          Chile                Colchagua Costa      1
300      Portugal                        Colares      1
369  South Africa               Cape South Coast      1
201        Greece                  Sterea Ellada      1
221        Israel                    Ella Valley      1
411   Switzerland                         Ticino      1
..            ...                            ...    ...
2       Argentina                          Other    889
81          Chile                   Maipo Valley    895
314      Portugal                           Port    903
128        France                       Provence   1021
301      Portugal                          Douro   1075
126        France           Languedoc-Roussillon   1082
70          Chile               Colchagua Valley   1201
129        France                   Rhône Valley   1318
403         Spain                      Catalonia   1352
124        France                      Champagne   1370
241         Italy                 Southern Italy   1439
234         Italy                  Central Italy   1530
130        France               Southwest France   1601
272   New Zealand                    Marlborough   1655
120        France                         Alsace   1680
127        France                   Loire Valley   1786
237         Italy             Northeastern Italy   1982
434            US                       New York   2428
240         Italy              Sicily & Sardinia   2545
6       Australia                South Australia   3004
243         Italy                         Veneto   3962
239         Italy                       Piedmont   4093
123        France                       Burgundy   4308
437            US                         Oregon   4589
1       Argentina               Mendoza Province   4742
407         Spain                 Northern Spain   4892
122        France                       Bordeaux   6111
242         Italy                        Tuscany   7281
442            US                     Washington   9750
422            US                     California  44508

[455 rows x 3 columns]

In [24]:
countries_reviewed.sort_values(by='country', ascending=True)

       country                       province    len
0      Albania                        Mirditë      2
1    Argentina               Mendoza Province   4742
2    Argentina                          Other    889
3    Australia                Australia Other    553
4    Australia                New South Wales    246
5    Australia                     Queensland      3
6    Australia                South Australia   3004
7    Australia                       Tasmania     47
8    Australia                       Victoria    613
9    Australia              Western Australia    491
26     Austria               Südoststeiermark     57
27     Austria                  Südsteiermark     64
28     Austria                  Thermenregion    122
29     Austria                     Traisental     24
30     Austria                         Vienna     54
35     Austria                    Weinviertel     54
32     Austria                         Wagram     16
33     Austria               Wagram-Donauland     75
34     Austria            Weinland Österreich     10
25     Austria                         Styria     15
36     Austria         Wiener Gemischter Satz      5
31     Austria                         Wachau    383
24     Austria                     Steiermark      7
37     Austria          Österreichischer Sekt     20
22     Austria               Niederösterreich    491
10     Austria                        Austria     19
12     Austria                      Carnuntum     70
13     Austria                      Donauland     22
14     Austria                      Eisenberg      3
15     Austria                        Kamptal    327
..         ...                            ...    ...
438         US                   Pennsylvania     50
437         US                         Oregon   4589
436         US                           Ohio     34
435         US                 North Carolina     20
434         US                       New York   2428
432         US                     New Jersey     24
433         US                     New Mexico     95
430         US                       Missouri     60
420         US                        America     27
421         US                        Arizona     39
431         US                         Nevada      1
423         US                       Colorado     30
424         US                    Connecticut      2
422         US                     California  44508
426         US                           Iowa      4
427         US                       Kentucky      4
428         US                  Massachusetts     10
429         US                       Michigan     25
425         US                          Idaho    136
444  US-France  Santa Barbara County-Condrieu      1
445    Ukraine                        Ukraine      5
451    Uruguay                     Montevideo      3
452    Uruguay                       Progreso      5
450    Uruguay                        Juanico     19
453    Uruguay                       San Jose     15
448    Uruguay                        Colonia      6
447    Uruguay                      Canelones     19
446    Uruguay                      Atlantida      4
449    Uruguay                    El Colorado      3
454    Uruguay                        Uruguay     18

[455 rows x 3 columns]

In [ ]:
countries_reviewed.sort_index()

In [ ]:
countries_reviewed.sort_values(by=['country','len'])

FInding the datatype of a variable is very easy. You can also find the datatypes of alll the features at once

In [ ]:
wine_reviews.price.dtype

In [ ]:
wine_reviews.dtypes

To explicitly convert a variable from one type to another we use `astype` function

In [ ]:
wine_reviews.points.astype('float64')

Imagine we want to replaec the name US to United States of America. We will now use the `replace` function

In [ ]:
wine_reviews.country.replace('US','United States of America')

# Plotting of Data

## Univariate plotting with pandas

In [ ]:
wine_reviews['country'].value_counts().head(10).plot.bar()

Let us now calculate the number of reviews with the range of points

In [ ]:
wine_reviews['points'].value_counts().sort_index().plot.bar()

In [ ]:
wine_reviews['points'].value_counts().sort_index().plot.line()

In [ ]:
wine_reviews['points'].value_counts().sort_index().plot.area()

The charts above work well for all the discrete variables. What if I want to plot a interval variable (eg: 10-20).We would have to plot a histogram and such graphs.

In [ ]:
wine_reviews['points'].plot.hist()

## Bivariate plotting with pandas

# Bivariate plotting with pandas

<table>
<tr>
<td><img src="https://i.imgur.com/bBj1G1v.png" width="350px"/></td>
<td><img src="https://i.imgur.com/ChK9zR3.png" width="350px"/></td>
</tr>
<tr>
<td style="font-weight:bold; font-size:16px;">Scatter Plot</td>
<td style="font-weight:bold; font-size:16px;">Hex Plot</td>
</tr>
<tr>
<td>df.plot.scatter()</td>
<td>df.plot.hexbin()</td>
</tr>
<tr>
<td>Good for interval and some nominal categorical data.</td>
<td>Good for interval and some nominal categorical data.</td>
</tr>
</table>

In [ ]:
wine_reviews[wine_reviews['price'] < 100].sample(100).plot.scatter(x='price', y='points')

A  **hex plot** aggregates points in space into hexagons, and then colors those hexagons based on the values within them:

In [ ]:
wine_reviews[wine_reviews['price'] < 100].plot.hexbin(x='price', y='points', gridsize=15)